# Form implementation generated from reading ui file 'fileHandling.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fileHandling(object):
    def setupUi(self, fileHandling):
        fileHandling.setObjectName("fileHandling")
        fileHandling.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fileHandling.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fileHandling)
        self.centralwidget.setObjectName("centralwidget")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(250, 80, 281, 251))
        self.lstScores.setObjectName("lstScores")
        self.lblScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScores.setGeometry(QtCore.QRect(300, 30, 191, 16))
        self.lblScores.setObjectName("lblScores")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(340, 380, 93, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.txtAverage = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAverage.setGeometry(QtCore.QRect(330, 460, 113, 22))
        self.txtAverage.setReadOnly(True)
        self.txtAverage.setObjectName("txtAverage")
        fileHandling.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fileHandling)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        fileHandling.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fileHandling)
        self.statusbar.setObjectName("statusbar")
        fileHandling.setStatusBar(self.statusbar)

        self.retranslateUi(fileHandling)
        QtCore.QMetaObject.connectSlotsByName(fileHandling)

    def retranslateUi(self, fileHandling):
        _translate = QtCore.QCoreApplication.translate
        fileHandling.setWindowTitle(_translate("fileHandling", "MainWindow"))
        self.lblScores.setText(_translate("fileHandling", "Student name and scores"))
        self.btnCalculate.setText(_translate("fileHandling", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fileHandling = QtWidgets.QMainWindow()
    ui = Ui_fileHandling()
    ui.setupUi(fileHandling)
    fileHandling.show()
    sys.exit(app.exec())
