# Form implementation generated from reading ui file 'fiancial planner.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbYearlyAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbYearlyAmount.setGeometry(QtCore.QRect(180, 100, 231, 21))
        self.lbYearlyAmount.setObjectName("lbYearlyAmount")
        self.txtyearlydeposit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtyearlydeposit.setGeometry(QtCore.QRect(480, 100, 113, 20))
        self.txtyearlydeposit.setObjectName("txtyearlydeposit")
        self.lbltarget = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltarget.setGeometry(QtCore.QRect(180, 170, 151, 20))
        self.lbltarget.setObjectName("lbltarget")
        self.txtTarget = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTarget.setGeometry(QtCore.QRect(480, 170, 113, 20))
        self.txtTarget.setObjectName("txtTarget")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(480, 230, 121, 22))
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(180, 230, 141, 16))
        self.lblPlan.setObjectName("lblPlan")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(480, 310, 131, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.iblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.iblTime.setGeometry(QtCore.QRect(190, 370, 91, 16))
        self.iblTime.setObjectName("iblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(490, 370, 113, 20))
        self.txtTime.setReadOnly(True)
        self.txtTime.setObjectName("txtTime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "financial planner"))
        self.lbYearlyAmount.setText(_translate("MainWindow", "Enter yearly deposit amount"))
        self.lbltarget.setText(_translate("MainWindow", "Enter target amount"))
        self.cmbPlan.setItemText(0, _translate("MainWindow", "Plan 2040"))
        self.cmbPlan.setItemText(1, _translate("MainWindow", "Plan 2050"))
        self.cmbPlan.setItemText(2, _translate("MainWindow", "Plan 2060"))
        self.lblPlan.setText(_translate("MainWindow", "Select Retirement Plan"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate Time Taken"))
        self.iblTime.setText(_translate("MainWindow", "Time Taken"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
