# Form implementation generated from reading ui file 'studentApp.ui'
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import pymysql as mdb


class Ui_studentApp(object):
    def setupUi(self, studentApp):
        studentApp.setObjectName("studentApp")
        studentApp.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentApp.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentApp)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStudent = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStudent.setGeometry(QtCore.QRect(50, 20, 721, 501))
        self.tbStudent.setObjectName("tbStudent")
        self.tbStudentInfo = QtWidgets.QWidget()
        self.tbStudentInfo.setObjectName("tbStudentInfo")
        self.lblStudentID = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentID.setGeometry(QtCore.QRect(220, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentID.setFont(font)
        self.lblStudentID.setObjectName("lblStudentID")
        self.lblStudentName = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentName.setGeometry(QtCore.QRect(220, 110, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentName.setFont(font)
        self.lblStudentName.setObjectName("lblStudentName")
        self.lblStudentScore = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentScore.setGeometry(QtCore.QRect(220, 140, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentScore.setFont(font)
        self.lblStudentScore.setObjectName("lblStudentScore")
        self.txtStudentID = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtStudentID.setGeometry(QtCore.QRect(310, 70, 113, 21))
        self.txtStudentID.setObjectName("txtStudentID")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtName.setGeometry(QtCore.QRect(310, 100, 113, 21))
        self.txtName.setObjectName("txtName")
        self.txtScore = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtScore.setGeometry(QtCore.QRect(310, 130, 113, 21))
        self.txtScore.setObjectName("txtScore")
        self.btnDisplayData = QtWidgets.QPushButton(parent=self.tbStudentInfo)
        self.btnDisplayData.setGeometry(QtCore.QRect(210, 220, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDisplayData.setFont(font)
        self.btnDisplayData.setObjectName("btnDisplayData")
        self.btnInsertData = QtWidgets.QPushButton(parent=self.tbStudentInfo)
        self.btnInsertData.setGeometry(QtCore.QRect(360, 220, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnInsertData.setFont(font)
        self.btnInsertData.setObjectName("btnInsertData")
        self.twStudentData = QtWidgets.QTableWidget(parent=self.tbStudentInfo)
        self.twStudentData.setGeometry(QtCore.QRect(210, 250, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.twStudentData.setFont(font)
        self.twStudentData.setObjectName("twStudentData")
        self.twStudentData.setColumnCount(0)
        self.twStudentData.setRowCount(0)
        self.tbStudent.addTab(self.tbStudentInfo, "")
        self.tbStudentGrade = QtWidgets.QWidget()
        self.tbStudentGrade.setObjectName("tbStudentGrade")
        self.lstStudentData = QtWidgets.QListWidget(parent=self.tbStudentGrade)
        self.lstStudentData.setGeometry(QtCore.QRect(230, 20, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstStudentData.setFont(font)
        self.lstStudentData.setObjectName("lstStudentData")
        self.btnExportData = QtWidgets.QPushButton(parent=self.tbStudentGrade)
        self.btnExportData.setGeometry(QtCore.QRect(300, 250, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExportData.setFont(font)
        self.btnExportData.setObjectName("btnExportData")
        self.tbStudent.addTab(self.tbStudentGrade, "")
        studentApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        studentApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentApp)
        self.statusbar.setObjectName("statusbar")
        studentApp.setStatusBar(self.statusbar)

        self.retranslateUi(studentApp)
        self.tbStudent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(studentApp)
        
        # Store reference to main window
        self.main_window = studentApp
        
        # Database connection variable
        self.connection = None
        
        # Connect button click events
        self.btnDisplayData.clicked.connect(self.display_data)
        self.btnInsertData.clicked.connect(self.insert_data)
        self.btnExportData.clicked.connect(self.export_data)
        
        # Connect tab change event
        self.tbStudent.currentChanged.connect(self.tab_changed)
        
        # Initialize application on form load
        self.form_load()

    def retranslateUi(self, studentApp):
        _translate = QtCore.QCoreApplication.translate
        studentApp.setWindowTitle(_translate("studentApp", "Student App"))
        self.lblStudentID.setText(_translate("studentApp", "Student ID"))
        self.lblStudentName.setText(_translate("studentApp", "Name"))
        self.lblStudentScore.setText(_translate("studentApp", "Score"))
        self.btnDisplayData.setText(_translate("studentApp", "Display Data"))
        self.btnInsertData.setText(_translate("studentApp", "Insert Data"))
        self.tbStudent.setTabText(self.tbStudent.indexOf(self.tbStudentInfo), _translate("studentApp", "Student Info"))
        self.btnExportData.setText(_translate("studentApp", "Export Data"))
        self.tbStudent.setTabText(self.tbStudent.indexOf(self.tbStudentGrade), _translate("studentApp", "Student Grade"))
    
    def form_load(self):
        #Form load event: Opens database connection, reads external file, and inserts data into database table
        try:
            # Open database connection
            self.open_connection()
            
            # Read data from external file and insert into database
            self.load_data_from_file()
            
            # Close database connection
            self.close_connection()
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Form load error: {str(e)}")
    
    self.btnInser.clicked.connect(self.insert_data)
    
    self.btnDisplay.clicked.conneect(self.display_data)
   
    def display_data(self):
        try:
            dbconnnection= mbd.connec(databse="student_project", user="bus442user", password="bus4442user_password", host = "localhost", port = 3306
            cursorobj = dbconnection.cursor()
            cursorobj.execute("selct * from student)
            
            data = cursorobj.fetchall()
            for line in data:
                 print(line)
                 self.1stdata.addItem(f"{line[0]} {line[1]} {line[2]}
        except Exception as e:
            print(e)
        finally:
            if(dbconnection):
                dbconnection.close()
            
    
    def insert_data(self):
        try:
            dbconnection = None
            # Add input validation
            student_id = self.int(self.txtId.text())
            student_name = self.int(self.txtName.text())
            student_score = self.int(self.txtAge.text())
            
            dbconnnection= mbd.connec(databse="student_project", user="bus442user", password="bus4442user_password", host = "localhost", port = 3306
            cursorobj = dbconnectio.cursor()
            cursorobj.execute("insert into student(studentid, studentname, age) values (%s, %s, %s)", [studentid, studentname,studentage ])
            
            dbconnection.commit()
            msg = QtWidgets.QMessageBox()
            msg.setText("Data inserted succesfully")
            msg.exec()
        except Exception as e:
            print(e)
        finally
            if(dbconnection):
               dbconnection.close()
            
            
           
   
    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentApp = QtWidgets.QMainWindow()
    ui = Ui_studentApp()
    ui.setupUi(studentApp)
    studentApp.show()
    sys.exit(app.exec())