# Form implementation generated from reading ui file 'studentgrade.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentGrade(object):
    def setupUi(self, StudentGrade):
        StudentGrade.setObjectName("StudentGrade")
        StudentGrade.resize(752, 600)
        self.centralwidget = QtWidgets.QWidget(parent=StudentGrade)
        self.centralwidget.setObjectName("centralwidget")
        self.lnlScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lnlScore.setGeometry(QtCore.QRect(230, 90, 61, 16))
        self.lnlScore.setObjectName("lnlScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(310, 90, 113, 20))
        self.txtScore.setObjectName("txtScore")
        self.bbnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bbnDisplay.setGeometry(QtCore.QRect(320, 150, 91, 23))
        self.bbnDisplay.setObjectName("bbnDisplay")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(180, 250, 47, 14))
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(250, 250, 113, 20))
        self.txtGrade.setReadOnly(True)
        self.txtGrade.setObjectName("txtGrade")
        StudentGrade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StudentGrade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 22))
        self.menubar.setObjectName("menubar")
        StudentGrade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StudentGrade)
        self.statusbar.setObjectName("statusbar")
        StudentGrade.setStatusBar(self.statusbar)

        self.retranslateUi(StudentGrade)
        QtCore.QMetaObject.connectSlotsByName(StudentGrade)

    def retranslateUi(self, StudentGrade):
        _translate = QtCore.QCoreApplication.translate
        StudentGrade.setWindowTitle(_translate("StudentGrade", "Student Grade"))
        self.lnlScore.setText(_translate("StudentGrade", "Enter Score"))
        self.bbnDisplay.setText(_translate("StudentGrade", "Display Grade"))
        self.lblGrade.setText(_translate("StudentGrade", "Grade"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentGrade = QtWidgets.QMainWindow()
    ui = Ui_StudentGrade()
    ui.setupUi(StudentGrade)
    StudentGrade.show()
    sys.exit(app.exec())
