# Form implementation generated from reading ui file 'tableWidgetExample.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tableWidgetExample(object):
    def setupUi(self, tableWidgetExample):
        tableWidgetExample.setObjectName("tableWidgetExample")
        tableWidgetExample.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        tableWidgetExample.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=tableWidgetExample)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(210, 80, 56, 17))
        self.btnDisplay.setObjectName("btnDisplay")
        self.tblStudentData = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblStudentData.setGeometry(QtCore.QRect(120, 110, 256, 192))
        self.tblStudentData.setObjectName("tblStudentData")
        self.tblStudentData.setColumnCount(0)
        self.tblStudentData.setRowCount(0)
        tableWidgetExample.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tableWidgetExample)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        tableWidgetExample.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tableWidgetExample)
        self.statusbar.setObjectName("statusbar")
        tableWidgetExample.setStatusBar(self.statusbar)

        self.retranslateUi(tableWidgetExample)
        QtCore.QMetaObject.connectSlotsByName(tableWidgetExample)

    def retranslateUi(self, tableWidgetExample):
        _translate = QtCore.QCoreApplication.translate
        tableWidgetExample.setWindowTitle(_translate("tableWidgetExample", "Table widget example"))
        self.btnDisplay.setText(_translate("tableWidgetExample", "Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tableWidgetExample = QtWidgets.QMainWindow()
    ui = Ui_tableWidgetExample()
    ui.setupUi(tableWidgetExample)
    tableWidgetExample.show()
    sys.exit(app.exec())
